# Generated by Django 3.1.7 on 2021-04-04 10:15

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210404_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_opponent',
            field=models.CharField(blank=True, default=games.models.opponent_default, max_length=100, null=True),
        ),
    ]
