# Generated by Django 3.0.8 on 2021-06-26 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210209_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='alb',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alb', to='gallery.Album'),
        ),
    ]
