# Generated by Django 3.0.8 on 2021-06-29 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210627_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='alb',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gallery.Album'),
        ),
    ]
